spring:
  application:
    name: spring-batch
  datasource:
    url:  jdbc:h2:tcp://localhost/C:/Jubin/dev/data/db/h2/hello/batch
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false